# Generated by Django 4.2.3 on 2023-07-13 08:52

from django.db import migrations, models
import django.db.models.deletion
import portfolio.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=11)),
                ('customer_name', models.CharField(max_length=110)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='portfolio/banners/')),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='portfolio', to='portfolio.category')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('image', models.ImageField(upload_to=portfolio.utils.upload_image_to_gallery)),
                ('portflio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio')),
            ],
        ),
    ]
