# Generated by Django 4.2.3 on 2023-07-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(related_name='portfolio', to='portfolio.category'),
        ),
    ]
