# Generated by Django 4.2.3 on 2023-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=110),
        ),
    ]
