# Generated by Django 4.2.3 on 2023-07-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Please Empty This Filed has Complete Automatically', null=True, unique=True),
        ),
    ]
