# Generated by Django 4.2.3 on 2023-07-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='persent',
            new_name='percent',
        ),
    ]
